<?php

namespace AppBundle\Repository;

/**
 * SubGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
